BackStageOnlineStore/Controllers/BackStageOrderController.cs
using OSLibrary.Sevices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BackStageOnlineStore.Controllers
{
    [Authorize]
    public class BackStageOrderController : Controller
    {
        //[HttpPost]
        //public ActionResult Index(int id)
        //{
        //    var orderid = id;
        //    return View();
        //}
        // GET: BackStageOrder
        public ActionResult SelectOrder()
        {
            OrdersService ordersService = new OrdersService();
            return View(ordersService.BackStageGetAllOrders());
        }
        [HttpPost]
        public ActionResult SelectOrderByAccount(string Account)
        {

            OrdersService ordersService = new OrdersService();
            return View(ordersService.BackStageGetAccountOrders(Account));
        }
        [HttpPost]
        public ActionResult SelectOrderByOrder_ID(int Order_ID)
        {
            //var Id = Order_ID;
            OrdersService ordersService = new OrdersService();
            //return View(ordersService.BackStageGetOrderByOrder_ID(Order_ID));
            return View(ordersService.BackStageGetOrderByOrder_ID(Order_ID));
        }

        public ActionResult CreateOrder()
        {
            return View();
        }
        public ActionResult SelectOrder_CheckIs0()
        {
            OrdersService ordersService = new OrdersService();
            return View(ordersService.BackStageGetOrder_CheckIs0());
        }
        public ActionResult SelectOrder_CheckIs1()
        {
            OrdersService ordersService = new OrdersService();
            return View(ordersService.BackStageGetOrder_CheckIs1());
        }
        public ActionResult SelectOrder_CheckIs2()
        {
            OrdersService ordersService = new OrdersService();
            return View(ordersService.BackStageGetOrder_CheckIs2());
        }
        public ActionResult SelectOrder_CheckIs3()
        {
            OrdersService ordersService = new OrdersService();
            return View(ordersService.BackStageGetOrder_CheckIs3());
        }
        public ActionResult SelectOrder_CheckIs4()
        {
            OrdersService ordersService = new OrdersService();
            return View(ordersService.BackStageGetOrder_CheckIs4());
        }


        //下面OrderDetails

        public ActionResult SelectOrderDetails()
        {
            var result = new Order_DetailsService();
            var list = result.BackStageGetAllOrderDetails();
            return View(list);
        }

        public ActionResult CreateOrderDetails()
        {
            return View();
        }

        public ActionResult UpdateOrderDetails()
        {
            return View();
        }
    }
}

BackStageOnlineStore/Views/BackStageOrder/CreateOrder.cshtml
@{
    ViewBag.Title = "CreateOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item ">
        <a href="@Url.Action("SelectOrder","BackStageOrder")">查詢訂單</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action("CreateOrder","BackStageOrder")">新增訂單</a>
    </li>
</ol>
<!-- Example DataTables Card-->
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> 新增訂單
    </div>
    <div class="row mt-2">
        <div class="col">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="">會員帳號</span>
                </div>
                <input type="text" class="form-control">
                <button type="button" class="btn btn-secondary">新增商品</button>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>商品編號</th>
                        <th>圖片</th>
                        <th>商品名稱</th>
                        <th>尺寸</th>
                        <th>數量</th>
                        <th>顏色</th>
                        <th>價格</th>
                        <th>刪除</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>XXXXXXXX</td>
                        <td>
                            <img src="http://fakeimg.pl/50x50?font=bebas" alt="">
                        </td>
                        <td>短褲</td>
                        <td>
                            <div class="col">
                                <select>
                                    <option value="">-</option>
                                    <option value="">S</option>
                                    <option value="">M</option>
                                    <option value="">L</option>
                                </select>
                            </div>
                        </td>
                        <td>
                            <div class="col">
                                <select>
                                    <option value="">-</option>
                                    <option value="">黑</option>
                                    <option value="">白</option>
                                    <option value="">藍</option>
                                </select>
                            </div>
                        </td>
                        <td>
                            <div class="col">
                                <select>
                                    <option value="">-</option>
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                </select>
                            </div>
                        </td>
                        <td>$500</td>
                        <td class="text-center">
                            <i class="fas fa-trash-alt"></i>
                        </td>
                    </tr>
                    <tr>
                        <td>XXXXXXXX</td>
                        <td>
                            <img src="http://fakeimg.pl/50x50?font=bebas" alt="">
                        </td>
                        <td>上衣</td>
                        <td>
                            <div class="col">
                                <select>
                                    <option value="">-</option>
                                    <option value="">S</option>
                                    <option value="">M</option>
                                    <option value="">L</option>
                                </select>
                            </div>
                        </td>
                        <td>
                            <div class="col">
                                <select>
                                    <option value="">-</option>
                                    <option value="">黑</option>
                                    <option value="">白</option>
                                    <option value="">藍</option>
                                </select>
                            </div>
                        </td>
                        <td>
                            <div class="col">
                                <select>
                                    <option value="">-</option>
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                </select>
                            </div>
                        </td>
                        <td>$800</td>
                        <td class="text-center">
                            <i class="fas fa-trash-alt"></i>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="offset-1"></div>
        <div class="col mt-2">
            <b>商品總價:</b>
            <b>1300</b>
        </div>
        <div class="col mt-2">
            <b>付款方式:</b>
            <select>
                <option value="">-</option>
                <option value="">貨到付款</option>
                <option value="">超商取貨付款</option>
            </select>
        </div>
    </div>
    <div class="row">
        <div class="offset-1"></div>
        <div class="col mt-2">
            <b>物流費:</b>
            <b>60</b>
        </div>
        <div class="col mt-2">
            <b>運送方式:</b>
            <select>
                <option value="">-</option>
                <option value="">宅配</option>
                <option value="">超商取貨</option>
            </select>
        </div>
    </div>
    <div class="row">
        <div class="offset-1"></div>
        <div class="col  mt-2">
            <b>總價:</b>
            <b>1360</b>
        </div>
        <div class="col mt-2 text-right">
            <button type="button" class="btn btn-secondary">新增訂單</button>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

BackStageOnlineStore/Views/BackStageOrder/CreateOrderDetails.cshtml
@{
    ViewBag.Title = "CreateOrderDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Home")">主頁</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action("SelectOrderDetails","BackStageOrder")">訂單明細</a>
    </li>
    <li class="breadcrumb-item active">新增訂單明細資料</li>
</ol>
<div class="row">
    <div class="col-12">
        <h4 class="mt-2">新增訂單明細資料</h4>
        <div class="container-fluid">
            <div class="row">
                <div class="col-6">
                    <span>
                        訂單編號：
                        <span>xxxxxxxx</span>
                    </span>
                    <div class="container mt-5 text-left">
                        <div class="row">
                            <div class="col-4 mt-2 ">
                                <b>產品編號</b>
                            </div>
                            <div class="col">
                                <select style="width:200px;">
                                    <option>Choose..</option>
                                </select>
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-4  mt-2">
                                <b>數量</b>
                            </div>
                            <div class="col">
                                <select style="width:200px;">
                                    <option>Choose..</option>
                                </select>
                            </div>
                        </div>
                        <div class="row mt-3">

                            <div class="col-4  mt-2">
                                <b>尺寸</b>
                            </div>
                            <div class="col">
                                <select style="width:200px;">
                                    <option>Choose..</option>
                                </select>
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-4  mt-2">
                                <b>顏色</b>
                            </div>
                            <div class="col">
                                <select style="width:200px;">
                                    <option>Choose..</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-4">
                        <div class="col text-center">
                            <a class="btn btn-secondary btn-block" href="@Url.Action("SelectOrderDetails","BackStageOrder")">取消</a>
                        </div>
                        <div class="col text-center bmr">
                            <a class="btn btn-success btn-block" href="#">儲存</a>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>

</div>

BackStageOnlineStore/Views/BackStageOrder/SelectOrder.cshtml
@model IEnumerable<OSLibrary.Models.Orders>

@{
    ViewBag.Title = "SelectOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<ol class="breadcrumb">
    <li class="breadcrumb-item ">
        <a href="@Url.Action("SelectOrder","BackStageOrder")">查詢訂單</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action("CreateOrder","BackStageOrder")">新增訂單</a>
    </li>
</ol>
<!-- Example DataTables Card-->

<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> 查詢訂單
    </div>
    <div class="row mt-1">
        <div class="col-4">
            <div class="input-group-append">
                @using (Html.BeginForm("SelectOrder", "BackStageOrder"))
                {
                    <input type="text" class="input_text" name="Order_ID">
                    <button class="btn btn-outline-secondary fa fa-search" type="submit"> 全部訂單</button>
                }
            </div>
            <div class="input-group-append">
                @using (Html.BeginForm("SelectOrderByOrder_ID", "BackStageOrder"))
                {
                    <input type="text" class="input_text" name="Order_ID" id="input_text">
                    <button class="btn btn-outline-secondary fa fa-search" type="submit"> 訂單編號 </button>
                }
            </div>
            <div class="input-group-append">
                @using (Html.BeginForm("SelectOrderByAccount", "BackStageOrder"))
                {
                    <input type="text" class="input_text" name="Account">
                    <button class="btn btn-outline-secondary fa fa-search" type="submit"> 會員帳號</button>
                }
            </div>
        </div>
        <div class="col-8">
            <div class="row mt-1">
                <div class="col">
                    <div class="input-group ">
                        <select class="custom-select">
                            <option selected>訂單日期</option>
                            <option value="1">出貨日期</option>
                        </select>
                        <input type="date" class="form-control" id="StartDate ">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary fa fa-angle-right" type="button" disabled></button>
                        </div>
                        <input type="date" class="form-control" id="EndDate ">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary fa fa-search" type="button"></button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-1">
                <div class="col">
                    <b> 訂單狀態:</b>
                    <button class="btn btn-outline-secondary fa fa-search" type="submit"> 未出貨 </button>
                    <button class="btn btn-outline-secondary fa fa-search" type="submit"> 已出貨 </button>
                    <button class="btn btn-outline-secondary fa fa-search" type="submit"> 已取貨 </button>
                    
                </div>
            </div>

        </div>
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>訂單編號</th>
                        <th>會員帳號</th>
                        <th>訂單日期</th>
                        <th>訂單狀態</th>
                        <th>出貨日期</th>
                        <th>總價</th>
                        <th>付款方式</th>
                        <th>運送方式</th>
                        <th>修改</th>
                        <th>刪除</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Order_ID</td>
                            <td>@item.Account</td>
                            <td>
                                @item.Order_Date
                            </td>

                            @switch (item.Order_Check)
                            {
                                case "0":
                                    <td> 新訂單</td>
                                    break;
                                case "1":
                                    <td>處理中 </td>break;
                                case "2":
                                    <td> 已出貨</td>
                                    break;
                                case "3":
                                    <td>已完成</td>
                                    break;
                                case "4":
                                    <td>已取消</td>
                                    break;
                                default:
                                    <td>退貨</td>
                                    break;
                            }
                            <td>
                                2018/05/25
                            </td>
                            <td>
                                @item.Total
                            </td>
                            <td>
                                @item.Pay
                            </td>
                            <td>
                                @item.Transport
                            </td>
                            <td class="text-center">
                                <i class="fas fa-pencil-alt"></i>
                            </td>
                            <td class="text-center">
                                <i class="fas fa-trash-alt"></i>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

BackStageOnlineStore/Views/BackStageOrder/SelectOrderByAccount.cshtml
@model IEnumerable<OSLibrary.Models.Orders>
@{
    ViewBag.Title = "SelectOrderByAccount";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<ol class="breadcrumb">
    <li class="breadcrumb-item ">
        <a href="@Url.Action(" SelectOrder","BackStageOrder")">查詢訂單</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action(" CreateOrder","BackStageOrder")">新增訂單</a>
    </li>
</ol>
<!-- Example DataTables Card-->

<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> 查詢訂單
    </div>
    <div class="row mt-1">
        <div class="col-4">
            <div class="input-group-append">
                @using (Html.BeginForm("SelectOrder", "BackStageOrder"))
                {
                    <input type="text" class="input_text" name="Order_ID">
                    <button class="btn btn-outline-secondary fa fa-search" type="submit"> 全部訂單</button>
                }
            </div>
            <div class="input-group-append">
                @using (Html.BeginForm("SelectOrderByOrder_ID", "BackStageOrder"))
                {
                    <input type="text" class="input_text" name="Order_ID" id="input_text">
                    <button class="btn btn-outline-secondary fa fa-search" type="submit"> 訂單編號 </button>
                }
            </div>
            <div class="input-group-append">
                @using (Html.BeginForm("SelectOrderByAccount", "BackStageOrder"))
                {
                    <input type="text" class="input_text" name="Account">
                    <button class="btn btn-outline-secondary fa fa-search" type="submit"> 會員帳號</button>
                }
            </div>
        </div>
        <div class="col-8">
            <div class="row mt-1">
                <div class="col">
                    <div class="input-group ">
                        <select class="custom-select">
                            <option selected>訂單日期</option>
                            <option value="1">出貨日期</option>
                        </select>
                        <input type="date" class="form-control" id="StartDate ">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary fa fa-angle-right" type="button" disabled></button>
                        </div>
                        <input type="date" class="form-control" id="EndDate ">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary fa fa-search" type="button"></button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-1">
                <div class="col">
                    <b> 訂單狀態:</b>
                </div>
                <div class="col">
                    @using (Html.BeginForm("SelectOrder_CheckIs0", "BackStageOrder"))
            {<button class="btn btn-outline-secondary fa fa-search" type="submit"> 新訂單 </button>
    }
                </div>
                <div class="col">
                    @using (Html.BeginForm("SelectOrder_CheckIs1", "BackStageOrder"))
            {<button class="btn btn-outline-secondary fa fa-search" type="submit"> 處理中 </button>
    }
                </div>
                <div class="col">
                    @using (Html.BeginForm("SelectOrder_CheckIs2", "BackStageOrder"))
            {<button class="btn btn-outline-secondary fa fa-search" type="submit"> 已出貨 </button>
    }
                </div>
                <div class="col">
                    @using (Html.BeginForm("SelectOrder_CheckIs3", "BackStageOrder"))
            {<button class="btn btn-outline-secondary fa fa-search" type="submit"> 已完成 </button>
    }
                </div>
                <div class="col">
                    @using (Html.BeginForm("SelectOrder_CheckIs4", "BackStageOrder"))
            {<button class="btn btn-outline-secondary fa fa-search" type="submit"> 已取消</button>
    }
                </div>
                <div class="col">
                    @using (Html.BeginForm("SelectOrder_CheckIs5", "BackStageOrder"))
            {<button class="btn btn-outline-secondary fa fa-search" type="submit"> 退貨</button>
    }
                </div>
            </div>

        </div>
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>訂單編號</th>
                        <th>會員帳號</th>
                        <th>訂單日期</th>
                        <th>訂單狀態</th>
                        <th>出貨日期</th>
                        <th>總價</th>
                        <th>付款方式</th>
                        <th>運送方式</th>
                        <th>修改</th>
                        <th>刪除</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Order_ID</td>
                            <td>@item.Account</td>
                            <td>
                                @item.Order_Date
                            </td>
                            <td>
                                @item.Order_Check
                            </td>
                            <td>
                                2018/05/25
                            </td>
                            <td>
                                @item.Total
                            </td>
                            <td>
                                @item.Pay
                            </td>
                            <td>
                               @item.Transport
                            </td>
                            <td class="text-center">
                                <i class="fas fa-pencil-alt"></i>
                            </td>
                            <td class="text-center">
                                <i class="fas fa-trash-alt"></i>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

BackStageOnlineStore/Views/BackStageOrder/SelectOrderByOrder_ID.cshtml
@model OSLibrary.Models.Orders

@{
    ViewBag.Title = "SelectOrderByOrder_ID";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<ol class="breadcrumb">
    <li class="breadcrumb-item ">
        <a href="@Url.Action("SelectOrder","BackStageOrder")">查詢訂單</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action("CreateOrder","BackStageOrder")">新增訂單</a>
    </li>
</ol>
<!-- Example DataTables Card-->

<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> 查詢訂單
    </div>
    <div class="row mt-1">
        <div class="col-4">
            <div class="input-group-append">
                @using (Html.BeginForm("SelectOrder", "BackStageOrder"))
                {
                    <input type="text" class="input_text" name="Order_ID">
                    <button class="btn btn-outline-secondary fa fa-search" type="submit"> 全部訂單</button>
                }
            </div>
            <div class="input-group-append">
                @using (Html.BeginForm("SelectOrderByOrder_ID", "BackStageOrder"))
                {
                    <input type="text" class="input_text" name="Order_ID" id="input_text">
                    <button class="btn btn-outline-secondary fa fa-search" type="submit"> 訂單編號 </button>
                }
            </div>
            <div class="input-group-append">
                @using (Html.BeginForm("SelectOrderByAccount", "BackStageOrder"))
                {
                    <input type="text" class="input_text" name="Account">
                    <button class="btn btn-outline-secondary fa fa-search" type="submit"> 會員帳號</button>
                }
            </div>
        </div>
        <div class="col-8">
            <div class="row mt-1">
                <div class="col">
                    <div class="input-group ">
                        <select class="custom-select">
                            <option selected>訂單日期</option>
                            <option value="1">出貨日期</option>
                        </select>
                        <input type="date" class="form-control" id="StartDate ">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary fa fa-angle-right" type="button" disabled></button>
                        </div>
                        <input type="date" class="form-control" id="EndDate ">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary fa fa-search" type="button"></button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-1">
                <div class="col">
                    <b> 訂單狀態:</b>
                </div>
                <div class="col">
                    @using (Html.BeginForm("SelectOrder_CheckIs0", "BackStageOrder"))
            {<button class="btn btn-outline-secondary fa fa-search" type="submit"> 新訂單 </button>
    }
                </div>
                <div class="col">
                    @using (Html.BeginForm("SelectOrder_CheckIs1", "BackStageOrder"))
            {<button class="btn btn-outline-secondary fa fa-search" type="submit"> 處理中 </button>
    }
                </div>
                <div class="col">
                    @using (Html.BeginForm("SelectOrder_CheckIs2", "BackStageOrder"))
            {<button class="btn btn-outline-secondary fa fa-search" type="submit"> 已出貨 </button>
    }
                </div>
                <div class="col">
                    @using (Html.BeginForm("SelectOrder_CheckIs3", "BackStageOrder"))
            {<button class="btn btn-outline-secondary fa fa-search" type="submit"> 已完成 </button>
    }
                </div>
                <div class="col">
                    @using (Html.BeginForm("SelectOrder_CheckIs4", "BackStageOrder"))
            {<button class="btn btn-outline-secondary fa fa-search" type="submit"> 已取消</button>
    }
                </div>
                <div class="col">
                    @using (Html.BeginForm("SelectOrder_CheckIs5", "BackStageOrder"))
            {<button class="btn btn-outline-secondary fa fa-search" type="submit"> 退貨</button>
    }
                </div>
            </div>

        </div>
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>訂單編號</th>
                        <th>會員帳號</th>
                        <th>訂單日期</th>
                        <th>訂單狀態</th>
                        <th>出貨日期</th>
                        <th>總價</th>
                        <th>付款方式</th>
                        <th>運送方式</th>
                        <th>修改</th>
                        <th>刪除</th>
                    </tr>
                </thead>
                <tbody>
                  
                        <tr>
                            <td>@Model.Order_ID</td>
                            <td>@Model.Account</td>
                            <td>
                                @Model.Order_Date
                            </td>
                            <td>
                                  @Model.Order_Check
                            </td>
                            <td>
                                2018/05/25
                            </td>
                            <td>
                                @Model.Total
                            </td>
                            <td>
                               @Model.Pay</option>
                                   
                            </td>
                            <td>
                               @Model.Transport
                            </td>
                            <td class="text-center">
                                <i class="fas fa-pencil-alt"></i>
                            </td>
                            <td class="text-center">
                                <i class="fas fa-trash-alt"></i>
                            </td>
                        </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>