BackStageOnlineStore/Controllers/BackStageProductController.cs
using OSLibrary.Sevices;
using OSLibrary.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BackStageOnlineStore.Controllers
{
    [Authorize]
    [RoutePrefix("Product")]
    public class BackStageProductController : Controller
    {
        [Route("")]
        // GET: BackStageProduct
        public ActionResult SelectProduct()
        {
            var result = new ProductService();
            var list = result.BackStageGetAllProducts();
            return View(list);
        }

        [Route("AddProduct")]
        public ActionResult CreateProduct()
        {
            return View();
        }

        [Route("UpdateProduct/{Product_ID}")]
        public ActionResult UpdateProduct(int Product_ID)
        {
            var service = new ProductService();
            return View(service.GetProductByProductID(Product_ID));
        }

        [HttpPost]
        public ActionResult Update(int Product_ID, string ProductName, decimal Price, string CategoryName, string Gender, string Online, string Comments)
        {
            var service = new ProductService();
            if(service.UpdateProducts(Product_ID, ProductName, Price, CategoryName, Gender, Online, Comments))
            {
                TempData["message"] = "更新成功";
            }
            else
            {
                TempData["message"] = "更新失敗，請聯絡客服";
            }
            return RedirectToAction("SelectProduct");
        }
    }
}

BackStageOnlineStore/Views/BackStageProduct/CreateProduct.cshtml
@{
    ViewBag.Title = "CreateProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Home")">主頁</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action("SelectProduct","BackStageProduct")">商品</a>
    </li>
    <li class="breadcrumb-item active">新增商品資料</li>
</ol>
<div class="row">
    <div class="col-12">
        <h4 class="mt-2">新增商品資料</h4>
        <div class="container-fluid">
            <div class="row">
                <div class="col-6">
                    <div class="container mt-5 text-left">
                        <div class="row  ">

                            <div class="col-4 mt-2 ">
                                <b>商品名稱</b>
                            </div>
                            <div class="col">
                                <input class="form-control" aria-describedby="basic-addon1" type="text">
                            </div>

                        </div>
                        <div class="row mt-3  ">

                            <div class="col-4  mt-2">
                                <b>價格</b>
                            </div>
                            <div class="col">
                                <input class="form-control" aria-describedby="basic-addon2" type="text">
                            </div>

                        </div>
                        <div class="row mt-3  ">

                            <div class="col-4  mt-2">
                                <b>性別</b>
                            </div>
                            <div class="col">
                                <select class="form-control">
                                    <option value="WOMEN">WOMEN</option>
                                    <option value="MEN">MEN</option>
                                    <option value="KIDS">KIDS</option>
                                </select>

                            </div>

                        </div>
                        <div class="row mt-3  ">

                            <div class="col-4  mt-2">
                                <b>種類</b>
                            </div>
                            <div class="col">
                                <select class="form-control">
                                    <option value="TOP">TOP</option>
                                    <option value="BOTTOM">BOTTOM</option>
                                    <option value="JUMPSUIT">JUMPSUIT</option>
                                    <option value="UNDERWEAR">UNDERWEAR</option>
                                </select>
                            </div>

                        </div>
                        <div class="row mt-3  ">

                            <div class="col-4  mt-2">
                                <b>顯示</b>
                            </div>
                            <div class="col">
                                <select class="form-control">
                                    <option value="上架中">上架中</option>
                                    <option value="已下架">已下架</option>
                                </select>
                            </div>

                        </div>
                        <div class="row mt-3  ">

                            <div class="col-4  mt-2">
                                <b>備註 ( 資訊 )</b>
                            </div>
                            <div class="col">
                                <textarea class="form-control" name="message" style=" height:150px;"></textarea>
                            </div>

                        </div>

                        <div class="row mt-4  ">
                            <div class="col text-center">
                                <a class="btn btn-secondary btn-block" href="@Url.Action("SelectProduct","BackStageProduct")">取消</a>
                            </div>
                            <div class="col text-center bmr">
                                <a class="btn btn-success btn-block" href="#">儲存</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

BackStageOnlineStore/Views/BackStageProduct/SelectProduct.cshtml
@model IEnumerable<OSLibrary.ViewModels.BackStageProductModel>
@{
    ViewBag.Title = "SelectProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Home")">主頁</a>
    </li>
    <li class="breadcrumb-item active">商品</li>
</ol>
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> 商品資料

    </div>
    <div class="card-body">

        <div class="table-responsive">

            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

                <thead>
                    <tr>
                        <th>編號</th>
                        <th>名稱</th>
                        <th>價格</th>
                        <th>性別</th>
                        <th>顯示</th>
                        <th style=" width:35px">進貨</th>
                        <th style=" width:35px">修改</th>
                        <th style=" width:35px">刪除</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>編號</th>
                        <th>名稱</th>
                        <th>價格</th>
                        <th>性別</th>
                        <th>顯示</th>
                        <th style=" width:35px">進貨</th>
                        <th style=" width:35px">修改</th>
                        <th style=" width:35px">刪除</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.ProductID</td>
                            <td>@item.Name</td>
                            <td>@String.Format("{0:0,0}", item.Price)</td>
                            <td>@item.Gender</td>
                            <td>@item.Online</td>
                            <td class="text-center">
                                <a href="#">
                                    <i class="fas fa-clipboard-check" style="color:#000"></i>
                                </a>
                            </td>
                            <td class="text-center">
                                <a href="Product/UpdateProduct/@item.ProductID">
                                    <i class="fas fa-pencil-alt" style="color:#000"></i>
                                </a>
                            </td>
                            <td class="text-center">
                                <a href="#">
                                    <i class="fas fa-trash-alt" style="color:#000"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>

            </table>

        </div>
        <div class="mt-2" style=" padding-left: 15px;">
            <a href="@Url.Action("CreateProduct","BackStageProduct")">
                <i class="fas fa-plus" style="font-size:1.5em; color:darkseagreen"></i>
            </a>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>

</div>

BackStageOnlineStore/Views/BackStageProduct/UpdateProduct.cshtml
@model OSLibrary.ViewModels.ProductModel
@{
    ViewBag.Title = "UpdateProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Home")">主頁</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action("SelectProduct","BackStageProduct")">商品</a>
    </li>
    <li class="breadcrumb-item active">修改商品資料</li>
</ol>
<div class="row">
    <div class="col-12">
        <h4 class="mt-2">修改商品資料</h4>
        <div class="container-fluid">
            <div class="row">
                <div class="col-6">
                    <div class="container mt-5 text-left">
                        @using (Html.BeginForm("Update", "BackStageProduct"))
                        {
                            <div class="row mt-3">
                                <div class="col-4 mt-2 ">
                                    <b>@Html.DisplayNameFor(model => model.ProductID)</b>
                                </div>
                                <div class="col">
                                    <input class="form-control" aria-describedby="basic-addon1" type="text" value="@Model.ProductID" name="Product_ID" readonly>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-4 mt-2 ">
                                    <b>@Html.DisplayNameFor(model => model.Name)</b>
                                </div>
                                <div class="col">
                                    <input class="form-control" aria-describedby="basic-addon2" type="text" value="@Model.Name" name="ProductName" readonly>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-4 mt-2">
                                    <b>@Html.DisplayNameFor(model => model.Price)</b>
                                </div>
                                <div class="col">
                                    @Html.TextBoxFor(model => model.Price, new { @class = "form-control", @name = "Price" })
                                    @Html.ValidationMessageFor(model => model.Price, null, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-4 mt-2">
                                    <b>@Html.DisplayNameFor(model => model.Gender)</b>
                                </div>
                                <div class="col">
                                    <select class="form-control" name="Gender">
                                        <option value="WOMEN" name="WOMEN">WOMEN</option>
                                        <option value="MEN" name="MEN">MEN</option>
                                        <option value="KIDS" name="KIDS">KIDS</option>
                                    </select>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-4 mt-2">
                                    <b>@Html.DisplayNameFor(model => model.CategoryName)</b>
                                </div>
                                <div class="col">
                                    <select class="form-control" name="CategoryName">
                                        <option value="TOP" name="TOP">TOP</option>
                                        <option value="BOTTOM" name="BOTTOM">BOTTOM</option>
                                        <option value="JUMPSUIT" name="JUMPSUIT">JUMPSUIT</option>
                                        <option value="UNDERWEAR" name="UNDERWEAR">UNDERWEAR</option>
                                    </select>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-4 mt-2">
                                    <b>@Html.DisplayNameFor(model => model.Online)</b>
                                </div>
                                <div class="col">
                                    <select class="form-control" name="Online">
                                        <option value="上架中" name="上架中">上架中</option>
                                        <option value="已下架" name="已下架">已下架</option>
                                    </select>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-4 mt-2">
                                    <b>@Html.DisplayNameFor(model => model.Comments)</b>
                                </div>
                                <div class="col">
                                    <textarea class="form-control" name="Comments" style="height:150px;"></textarea>
                                </div>
                            </div>
                            <div class="row mt-4">
                                <div class="col text-center">
                                    <a class="btn btn-secondary btn-block" href="@Url.Action("SelectProduct","BackStageProduct")">取消</a>
                                </div>
                                <div class="col text-center bmr">
                                    <button class="btn btn-success btn-block" type="submit">儲存</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>