BackStageOnlineStore/Controllers/BackStageEmployeeController.cs
using OSLibrary.Models;
using OSLibrary.Sevices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BackStageOnlineStore.Controllers
{
    [Authorize]
    [RoutePrefix("Employees")]
    public class BackStageEmployeeController : Controller
    {
        [Route("Index")]
        // GET: BackStageEmployee
        public ActionResult SelectEmployee()
        {
            var result = new EmployeeService();
            var list = result.BackStageGetEmployeeByAll();
            return View(list);
        }

        [Route("CreateEmployee")]
        public ActionResult CreateEmployee(string Account)
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateSingle(string Name, string Account, string Password, DateTime Birthday,
            string Email, string Phone, string Address)
        {
            EmployeeService employeeService = new EmployeeService();
            var message = "";
            if (employeeService.CreateEmployee(Name, Account, Password, Birthday, Email, Phone, Address))
            {
                TempData[message] = "新增成功";
            }
            else
            {
                TempData[message] = "無法新增，請聯絡客服";
            }
            return RedirectToAction("SelectEmployee");
        }

        [Route("UpdateEmployee/{Account}")]
        public ActionResult UpdateEmployee(string Account)
        {
            var result = new EmployeeService();
            return View(result.BackStageGetEmployeeByAccount(Account));
        }

        [HttpPost]
        public ActionResult UpdateEmployeeChange(string Name, string Account, string Password, DateTime Birthday,
            string Email, string Phone, string Address)
        {
            EmployeeService employeeService = new EmployeeService();
            if (employeeService.ChangeEmployee(Name, Account, Password, Birthday, Email, Phone, Address))
            {
                TempData["message"] = "更換成功";
            }
            else
            {
                TempData["message"] = "無法更新，請聯絡客服";
            }
            return RedirectToAction("SelectEmployee");
        }

        [HttpPost]
        public ActionResult DeleteEmployee(string Account)
        {
            var service = new EmployeeService();
            if(service.DeleteEmployee(Account))
            {
                TempData["message"] = "刪除成功";
            }
            else
            {
                TempData["message"] = "無法刪除，請聯絡克服";
            }
            return RedirectToAction("SelectEmployee");
        }
    }
}

BackStageOnlineStore/Views/BackStageEmployee/CreateEmployee.cshtml
@model OSLibrary.ViewModels.EmployeeModel
@{
    ViewBag.Title = "CreateEmployee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Home")">主頁</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action("SelectEmployee","BackStageEmployee")">員工</a>
    </li>
    <li class="breadcrumb-item active">新增員工資料</li>
</ol>
<div class="row">
    <div class="col-12">
        <h4 class="mt-2">新增員工資料</h4>
        <div class="container-fluid">
            <div class="row">
                <div class="col-6">
                    <div class="container mt-5 text-left">
                        @using (Html.BeginForm("CreateSingle", "BackStageEmployee"))
                        {
                        <div class="row">
                            <div class="col-4 mt-2 ">
                                <b>@Html.DisplayNameFor(model=>model.Name)</b>
                            </div>
                            <div class="col">
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @type = "text", @name = "Name"})
                                @Html.ValidationMessageFor(model=>model.Name, null, new { @class = "text-danger"})
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-4 mt-2">
                                <b>@Html.DisplayNameFor(model => model.Account)</b>
                            </div>
                            <div class="col">
                                @Html.TextBoxFor(model => model.Account, new { @class = "form-control", @type = "text", @name = "Account" })
                                @Html.ValidationMessageFor(model => model.Account, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-4 mt-2">
                                <b>@Html.DisplayNameFor(model => model.Password)</b>
                            </div>
                            <div class="col">
                                @Html.TextBoxFor(model => model.Password, new { @class = "form-control", @type = "Password", @name = "Password" })
                                @Html.ValidationMessageFor(model => model.Password, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-4 mt-2">
                                <b>@Html.DisplayNameFor(model => model.Birthday)</b>
                            </div>
                            <div class="col">
                                @Html.TextBoxFor(model => model.Birthday, new { @class = "form-control", @type = "text", @name = "Birthday" })
                                @Html.ValidationMessageFor(model => model.Birthday, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-4  mt-2">
                                <b>@Html.DisplayNameFor(model => model.Email)</b>
                            </div>
                            <div class="col">
                                @Html.TextBoxFor(model=>model.Email, new { @class = "form-control", @type = "text", @name = "Birthday" })
                                @Html.ValidationMessageFor(model=>model.Email, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row mt-3">

                            <div class="col-4  mt-2">
                                <b>@Html.DisplayNameFor(model => model.Phone)</b>
                            </div>
                            <div class="col">
                                @Html.TextBoxFor(model=>model.Phone, new { @class = "form-control", @type = "text", @name = "Phone" })
                                @Html.ValidationMessageFor(model=>model.Phone, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-4  mt-2">
                                <b>@Html.DisplayNameFor(model => model.Address)</b>
                            </div>
                            <div class="col">
                                @Html.TextBoxFor(model=>model.Address, new { @class = "form-control", @type = "text", @name = "Phone" })
                                @Html.ValidationMessageFor(model=>model.Address, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row mt-4">
                            <div class="col text-center">
                                <a class="btn btn-secondary btn-block" href="@Url.Action("SelectEmployee", "BackStageEmployee")">取消</a>
                            </div>
                            <div class="col text-center bmr">
                                <button class="btn btn-success btn-block" type="submit">儲存</button>
                            </div>
                        </div>
                        }
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

BackStageOnlineStore/Views/BackStageEmployee/SelectEmployee.cshtml
@model IEnumerable<OSLibrary.ViewModels.EmployeeModel>
@{
    ViewBag.Title = "SelectEmployee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Home")">主頁</a>
    </li>
    <li class="breadcrumb-item active">員工</li>
</ol>
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> 員工資料

    </div>
    <div class="card-body">
        
        <div class="table-responsive">
            @using (Html.BeginForm("DeleteEmployee", "BackStageEmployee"))
            {
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

                <thead>
                    <tr>
                        <th>姓名</th>
                        <th>帳號 </th>
                        <th>電話 </th>
                        <th>生日</th>
                        <th style=" width:35px">修改</th>
                        <th style=" width:35px">刪除</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>姓名</th>
                        <th>帳號 </th>
                        <th>電話 </th>
                        <th>生日</th>
                        <th style=" width:35px">修改</th>
                        <th style=" width:35px">刪除</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.Account</td>
                            <td>@item.Phone</td>
                            <td>@item.Birthday.ToShortDateString().ToString()</td>
                            <td class="text-center">
                                <a href="/Employees/UpdateEmployee/@item.Account">
                                    <i class="fas fa-pencil-alt" style=" color:#000"></i>
                                </a>
                            </td>
                            <td class="text-center">
                                <button type="submit" onclick="return confirm('確定要刪除?')">
                                    <i class="fas fa-trash-alt" style="color:#000"></i>
                                </button>
                                <input type="hidden" name="Account" value="@item.Account" />
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            }
        </div>
        <div class="mt-2" style=" padding-left: 15px;">
            <a href="@Url.Action("CreateEmployee","BackStageEmployee")">
                <i class="fas fa-user-plus " style="font-size:1.5em; color:darkseagreen"></i>
            </a>
        </div>
    </div>
    
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>

</div>

BackStageOnlineStore/Views/BackStageEmployee/UpdateEmployee.cshtml
@model OSLibrary.ViewModels.EmployeeModel
@{
    ViewBag.Title = "UpdateEmployee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Home")">主頁</a>
    </li>
    <li class="breadcrumb-item">
        <a href="@Url.Action("SelectEmployee","BackStageEmployee")">員工</a>
    </li>
    <li class="breadcrumb-item active">修改員工資料</li>
</ol>
<div class="row">
    <div class="col-12">
        <h4 class="mt-2">修改員工資料</h4>
        <div class="container-fluid">
            <div class="row">
                <div class="col-6">
                    <div class="container mt-5 text-left">
                        @using (Html.BeginForm("UpdateEmployeeChange", "BackStageEmployee"))
                        {

                        <div class="row">
                            <div class="col-4 mt-2 ">
                                <b>@Html.DisplayNameFor(model=>model.Name)</b>
                            </div>
                            <div class="col">
                                <input class="form-control" aria-describedby="basic-addon1" type="text" value="@Model.Name" name="Name" readonly>
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-4 mt-2">
                                <b>@Html.DisplayNameFor(model => model.Account)</b>
                            </div>
                            <div class="col">
                                <input class="form-control" aria-describedby="basic-addon2" type="text" value="@Model.Account" name="Account" readonly>
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-4 mt-2">
                                <b>@Html.DisplayNameFor(model => model.Password)</b>
                            </div>
                            <div class="col">
                                @Html.TextBoxFor(model => model.Password, new { @class = "form-control", @type = "Password", @name = "Password" })
                                @Html.ValidationMessageFor(model => model.Password, null, new { @class = "text-danger"})
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-4 mt-2">
                                <b>@Html.DisplayNameFor(model => model.Birthday)</b>
                            </div>
                            <div class="col">
                                <input class="form-control" aria-describedby="basic-addon4" type="text" value="@Model.Birthday.ToShortDateString().ToString()" name="Birthday">
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-4 mt-2">
                                <b>@Html.DisplayNameFor(model => model.Email)</b>
                            </div>
                            <div class="col">
                                <input class="form-control" aria-describedby="basic-addon5" type="text" value="@Model.Email" name="Email">
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-4 mt-2">
                                <b>@Html.DisplayNameFor(model => model.Phone)</b>
                            </div>
                            <div class="col">
                                <input class="form-control" aria-describedby="basic-addon6" type="text" value="@Model.Phone" name="Phone">
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-4 mt-2">
                                <b>@Html.DisplayNameFor(model => model.Address)</b>
                            </div>
                            <div class="col">
                                <input class="form-control" aria-describedby="basic-addon7" type="text" value="@Model.Address" name="Address">
                            </div>
                        </div>
                        <div class="row mt-4">
                            <div class="col text-center">
                                <a class="btn btn-secondary btn-block" href="@Url.Action("SelectEmployee", "BackStageEmployee")">取消</a>
                            </div>
                            <div class="col text-center bmr">
                                <button class="btn btn-success btn-block" type="submit">儲存</button>
                            </div>
                        </div>

                        }

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>